name: AWM
favicon: null
layout_spectrum: 0.7903219948057085
typography_spectrum: 0.5311246307101101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17888705735094845
  lightness: 0.3306073707062751
  saturation: 0.7117463110480458
  rhythmicContrast: 0.8752152100205421
purpose: []
